export type AppSettings = {
  video_device: string;
  video_width: number;
  video_height: number;
  video_fps: number;
  video_fourcc?: string | null;
  video_encoder: string;
  video_encoder_preset?: string | null;
  video_bitrate?: string | null;
  audio_device?: number | string | null;
  audio_sample_rate: number;
  audio_channels: number;
  audio_block_size: number;
  audio_playback_gain: number;
  audio_metrics_interval_ms: number;
  mediamtx_webrtc_url: string;
  video_algorithm: string;
  audio_algorithm: string;
};
export type Device = { id: string | number | null; name: string; available: boolean; channels?: number; max_channels?: number; default_sample_rate?: number; supported_sample_rates?: number[]; max_sample_rate?: number | null; supports_configured_sample_rate?: boolean; sample_rate_error?: string | null; sample_rate_errors?: Record<number, string>; stable?: boolean };
